apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sparkWorkerApp
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sparkWorkerApp
    spec:
      hostname: spark-worker-host
      containers:
        - name: spark-worker
          image: patelriyad/pa4:my-spark
          imagePullPolicy: Always
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "1"
            - name: SPARK_HOME
              value: "/opt/spark"
            - name: SPARK_LOCAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 7078
            - containerPort: 7079
            - containerPort: 8081
          command: ["/bin/bash", "-c"]
          args:
            - |
              ${SPARK_HOME}/sbin/start-worker.sh spark://spark-master-svc:7077 \
              --properties-file ${SPARK_HOME}/sbin/spark-config.conf
