# Use a Python base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy only the consumer code
COPY dbConsumer.py .

# Expose necessary ports (if applicable)
EXPOSE 9092

# Command to run the consumer
CMD ["python", "dbConsumer.py"]