# Use a Python base image
FROM python:3.9-slim

# Set working directory (can be any folder inside the container)
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy only the producer code
COPY iot.py .

# Expose the necessary ports
EXPOSE 9092 

# Command to run the producer
CMD ["python", "iot.py"]