apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-driver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkDriverApp
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: sparkDriverApp
    spec:
      hostname: spark-driver-host
      nodeSelector:
        kubernetes.io/hostname: kubemaster
      containers:
        - name: spark-driver
          image: 192.168.5.226:5000/spark:v3.4.0
          imagePullPolicy: Always
          env:
            - name: SPARK_LOCAL_IP
              value: "spark-driver-host"
            - name: SPARK_HOME
              value: "/opt/spark"
          ports:
            - containerPort: 4040
            - containerPort: 7076
            - containerPort: 7079
          
          command: ["tail"]
          args: ["-f", "/dev/null"]
            # command: ["$(SPARK_HOME)/bin/spark-submit"]
            # args: ["--master", "spark://spark-master-svc:7077", "--properties-file",
            # "$(SPARK_HOME)/conf/spark-driver.conf", "$(SPARK_HOME)/examples/src/main/python/workers.py", "/alice_in_wonderland.txt"]
